import { Inter } from "next/font/google";
import "./globals.css";

import logo from './assets/logo.png';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Retrak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
        <link rel="icon" href={logo.src} />
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>

      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
